import { DEFAULT_ITEM_PRECISION } from "../config/constants";

export default {
  estimate_id: null,
  item_id: null,
  name: '',
  title: '',
  description: null,
  quantity: 1,
  price: 0,
  precision_price: 0,
  status: null,
  status_name: null,
  precision:DEFAULT_ITEM_PRECISION,
  discount_type: 'fixed',
  discount_val: 0,
  discount: 0,
  total: 0,
  sub_total: 0,
  totalTax: 0,
  totalSimpleTax: 0,
  totalCompoundTax: 0,
  tax: 0,
  taxes: [],
  ieps: 0,
}
